import { createContext, useContext, useEffect, useState } from "react";

// Context'in adını büyük harflerle yazdık
const LangContext = createContext();

export const LangContextProvider = ({ children }) => {
  // Dil verileri
  const messages = {
    en: {
      "signin": "Login",
      "exit": "Exit",
      "language": "Language",
      "AboutUs": "About Us",
      "prof" : "Profile",
      "Products": "Products",
      "Menu": "Menu",
      "Opportunities": "Opportunities",
      "Contact": "Contact",
      "contact": "Contact",
      "myshopping": "My shopping",
      "special": "Special for you",
      "Mybox": "My box",
      "service": "Our Services",
      "closeCom": "Close Company",
      "openCom": "Open Company",
      "goLink": "Go to Link",
      "comp1title1": "Summer Opportunities",
      "comp1title2": "Legendary Friday",
      "comp1title3": "Legendary Discount",
      "comp1p": "only available for chosen cards",
      "goProducts": "Go Products",
      "winterDisc": "Winter Discounts",
      "winterDiscP": "don't miss the products",
      "company2T1": "Don't Miss the Opportunities Click Now",
      "company2T2": "Offers Valid for Select Cards",
      "company2T3": "Click for Discount Code",
      "whatsnew":"What's on sale?",
      "yourname": "Login Name",
      "yourpass": "Password",
      "login": "Login",
      "createLog": "Create Account",
      "SignIn": "Sign In",
      "email": "Email",
      "Password": "Password",
      "Name": "Name",
      "Surname": "Surname",
      "SignUp": "Sign Up",
      "ShowT": "Welcome!",
      "ShowH": "ONE LAST STEP LEFT",
      "ShowP": "Enter the code sent to your email address to verify your account.",
      "ShowBt1": "Confirm",
      "ShowBt2": "Retrieve Code",
      "closetCompT" : "Huge Discount For Closets!",
      "closetCompP" : "(avaliable for select cards)",
      "closetCompT1" : "Succesfull Seller",
      "closetCompT2" : "2500+ Fav",
      "closetCompB" : "go to product",
      "navSearch" : "Looking for?",
      "navListS1": "Top",
      "navListS2": "Bottom",
      "navListS3": "Home",
      "navListS6": "Jewerly",
      "navListSI1": "Sweater",
      "navListSI2": "Blouse",
      "navListSI3": "Skirt",
      "navListSI4": "Pants",
      "navListSI5": "carpet",
      "navListSI6": "cabinet",
      "navListSI11": "Ring",
      "navListSI12": "Necklace",
      "filterT" :"filter products" , 
      "filterI1" :"Size",
      "filterI2" :"Color",
      "filterI3" :" Wage Rate" ,
      "filterIT1" : "body size",
      "filterIT2" : "lenght",
      "filterIT3" : "width",
      "filterIO1" : "white",
      "filterIO2" : "black",
      "filterIO3" : "beige",
      "filterIO4" : "red",
      "filterIO5" : "yellow",
      "filterIO6" : "blue",
      "lookat" : "Similiar Products",
      "alertsuccT": "Successfully added to the cart!",
      "alertsuccD": "You can check the product in your cart",
      "alerterrT": "Product could not be added to the cart",
      "alerterrD": "You must log in first",
      "commT": "Reviews",
      "commTP": "Photo comments",
      "quesAns":"Q&A with seller",
      "addBasket":"add to basket",
      "throwBasket":"remove from basket",
      "question":"client's question",
      "answer":"seller's answer",
      "noProductAlertT":"There's no products here.",
      "noProductAlertP":"You haven't added any products.",
      "pricesT":"Total" , 
      "alladresslink":"See all adresses",
      "adress1":"Home adress 1",
      "adress2":"Home adress 2",
      "adressT":"My Registered Addresses",
      "information":"My Information",
      "namesurn":"Name",
      "emaill":"Email",
      "orderT":"My Orders",
      "allorders":"see all",
      "favT":"My Favorites",
      "cargo":"cargo",
      "productinfos" :"product details",
      "productsize":"size",
      "totalstock":"total stock:",
      "productcolor" :"product color",
      "sortingProducts":"list products",
      "showMore" : "Show more",
      "showAll" :"Show all",
      "mostLiked" :"Most loved ones",
      "liked" :"Loved ones",
      "lessLiked" :"Less loved ones",
      "favProducts" :"Favorite products",
      "noProductAlert" : "There are no products added  yet.",
      "comingFromYou" :"Coming from you",
      "photoComments": "Comments with photos",
      "yourComments" :"Your comments",
      "star" : "star",
      "productsOfSomething":"products",
      "phone":"Phone",
      "socialMedia":"Social Media",


      
    },
    tr: {
      "signin": "Giriş",
      "exit": "Çıkış",
      "language": "Dil Seçenekleri",
      "AboutUs": "Hakkımızda",
      "prof" : "Profil",
      "Products": "Ürünler",
      "Menu": "Menü",
      "Opportunities": "Fırsatlar",
      "Contact": "İletişim",
      "contact": "İletişim",
      "myshopping": "Alışverişlerim",
      "special": "Size özel",
      "Mybox": "Sepetim",
      "service": "Hizmetlerimiz",
      "closeCom": "Reklamı Kapat",
      "openCom": "Reklamı Aç",
      "goLink": "Linke Git",
      "comp1title1": "Yaz Fırsatları",
      "comp1title2": "Efsane Cuma",
      "comp1title3": "Efsane İndirimler",
      "comp1p": "Sadece bazı kartlar için geçerli",
      "goProducts": "Ürünlere Git",
      "winterDisc": "Kış İndirimleri",
      "winterDiscP": "Ürünleri kaçırma",
      "company2T1": "Fırsatları Kaçırma Hemen Tıkla",
      "company2T2": "Belirli Kartlar İçin Geçerli Fırsatlar",
      "company2T3": "İndirim Kodu İçin Tıkla",
      "whatsnew":"İndirimde Neler Var?",
      "yourname": "Kullanıcı Adınız",
      "yourpass": "Şifreniz",
      "login": "Giriş Yap",
      "createLog": "Hesap Oluştur",
      "SignIn": "Giriş Yap",
      "email": "Email",
      "Password": "Şifre",
      "Name": "İsim",
      "Surname": "Soyisim",
      "SignUp": "Kaydol",
      "ShowT": "Aramıza Hoşgeldin",
      "ShowH": "SON BİR ADIM KALDI",
      "ShowP": "Hesabınızın onayı için mail adresinize gelen kodu giriniz",
      "ShowBt1": "Onayla",
      "ShowBt2": "Kodu Yeniden Al",
      "closetCompT" : "Dolaplarda Dev Kampanya!",
      "closetCompP" : "(belli kartlar için geçerli)",
      "closetCompT1" : "Başarılı Satıcı",
      "closetCompT2" : "2500+ Fav",
      "closetCompB" : "ürüne git",
      "navSearch" : "Ne aradınız?",
      "deneme" : "deneme",
      "navListS1" :"Üst Giyim",
      "navListS2" :"Alt Giyim",
      "navListS3" :"Ev",
      "navListS6" :"Takı",
      "navListSI1" :"kazak",
      "navListSI2" :"bluz",
      "navListSI3" :"etek",
      "navListSI4" :"pantalon",
      "navListSI5" :"halı",
      "navListSI6" :"dolap",
      "navListSI11" :"yüzük",
      "navListSI12" :"kolye",
      "filterT" :"ürünleri filtrele" , 
      "filterI1" :"Ölçü",
      "filterI2" :"Renk",
      "filterI3" :"Fiyat Aralığı" ,
      "filterIT1" : "beden ölçüsü",
      "filterIT2" : "uzunluk",
      "filterIT3" : "genişlik",
      "filterIO1" : "beyaz",
      "filterIO2" : "siyah",
      "filterIO3" : "nude",
      "filterIO4" : "kırmızı",
      "filterIO5" : "sarı",
      "filterIO6" : "mavi",
      "lookat" : "Benzer Ürünler",
      "alertsuccT":"Başarıyla sepete eklendi!",
      "alertsuccD" :"Ürüne sepette bakabilirsiniz", 
      "alerterrT" :"Ürün sepete eklenemedi",
      "alerterrD":"Öncelikle giriş yapmalısınız", 
      "commT":"Yorumlar",
      "commTP": "Fotoğraflı yorumlar",
      "quesAns":"Soru-Cevap",
      "addBasket":"sepete ekle",
      "throwBasket" :"sepetten çıkar",
      "question":"müşterinin sorusu",
      "answer":"satıcının cevabı",
      "noProductAlertT":"Burada bir ürün yok.",
      "noProductAlert":"ürün eklemediniz",
      "pricesT":"Toplam" ,     
      "alladresslink":"Tüm adresleri gör",
      "adress1":"Ev adresi 1",
      "adress2":"Ev adresi 2",
      "adressT":"Kayıtlı Adreslerim",
      "information":"Bilgilerim",
      "namesurn":"Adınız",
      "emaill":"Email",
      "orderT":"Siparişlerim",
      "allorders":"hepsini gör",
      "favT":"Favorilerim",
      "cargo":"kargo",
      "productinfos" :"ürün detayları",
      "productsize":"beden",
      "totalstock":"toplam stok:",
      "productcolor" :"ürün rengi",
      "sortingProducts":"ürünleri listele",
      "showMore" : "Daha fazla göster",
      "showAll" :"Hepsini göster",
      "mostLiked" :"En sevilenler",
      "liked" :"Sevilenler",
      "lessLiked" :"Daha az sevilenler",
      "favProducts" :"Favori ürünler",
      "noProductAlert" : "Henüz eklenmiş ürün yok.",
      "comingFromYou" :"Sizden gelenler",
      "photoComments": "Fotoğraflı yorumlar",
      "yourComments" :"Yorumlarınız",
      "star" : "yıldız",
      "productsOfSomething":"ürünleri",
      "phone":"Telefon",
      "socialMedia":"Sosyal Medya",
  
    
     },

    fr : {
      "signin": "Connexion",
      "exit": "Déconnexion",
      "language": "Options de langue",
      "AboutUs": "À propos de nous",
      "prof" : "Profil",
      "Products": "Produits",
      "Menu": "Menu",
      "Opportunities": "Opportunités",
      "Contact": "Contact",
      "contact": "Contact",
      "myshopping": "Mes achats",
      "special": "Spécial pour vous",
      "Mybox": "Mon panier",
      "service": "Nos services",
      "closeCom": "Fermer la publicité",
      "openCom": "Ouvrir la publicité",
      "goLink": "Aller au lien",
      "comp1title1": "Offres d'été",
      "comp1title2": "Black Friday",
      "comp1title3": "Super réductions",
      "comp1p": "Valable uniquement pour certaines cartes",
      "goProducts": "Aller aux produits",
      "winterDisc": "Réductions d'hiver",
      "winterDiscP": "Ne manquez pas les produits",
      "company2T1": "Ne manquez pas les offres, cliquez maintenant",
      "company2T2": "Offres valables pour certaines cartes",
      "company2T3": "Cliquez pour le code de réduction",
      "whatsnew":"Ce qui est en vente",
      "yourname": "Votre nom",
      "yourpass": "Votre mot de passe",
      "login": "Se connecter",
      "createLog": "Créer un compte",
      "SignIn": "Se connecter",
      "email": "Email",
      "Password": "Mot de passe",
      "Name": "Prénom",
      "Surname": "Nom",
      "SignUp": "S'inscrire",
      "ShowT": "Bienvenue parmi nous",
      "ShowH": "IL NE RESTE PLUS QU'UNE ÉTAPE",
      "ShowP": "Entrez le code envoyé à votre adresse e-mail pour confirmer votre compte",
      "ShowBt1": "Confirmer",
      "ShowBt2": "Recevoir le code à nouveau",
      "closetCompT": "Grande campagne dans les placards !",
      "closetCompP": "(valable pour certaines cartes)",
      "closetCompT1": "Vendeur réussi",
      "closetCompT2": "2500+ Favoris",
      "closetCompB": "Aller au produit",
      "navSearch": "Que cherchez-vous?",
      "deneme": "essai",
      "navListS1": "Hauts",
      "navListS2": "Bas",
      "navListS3": "Maison",
      "navListS6": "Cadeau de Bijoux",
      "navListSI1": "Pull",
      "navListSI2": "Blouse",
      "navListSI3": "Jupe",
      "navListSI4": "Pantalon",
      "navListSI5": "etat",
      "navListSI6": "placard",
      "navListSI11": "Bague",
      "navListSI12": "Collier",
      "filterT" :"produits filtrants" , 
      "filterI1": "Taille",
      "filterI2": "Couleur",
      "filterI3": "Taux salarial",
      "filterIT1": "taille du corps",
      "filterIT2": "longueur",
      "filterIT3": "largeur",
      "filterIO1": "blanc",
      "filterIO2": "noir",
      "filterIO3": "beige",
      "filterIO4": "rouge",
      "filterIO5": "jaune",
      "filterIO6": "bleu",
      "lookat": "Produits Similaires",
      "alertsuccT": "Ajouté au panier avec succès !",
      "alertsuccD": "Vous pouvez consulter le produit dans votre panier",
      "alerterrT": "Le produit n'a pas pu être ajouté au panier",
      "alerterrD": "Vous devez d'abord vous connecter",
      "commT": "Avis",
      "commTP": "Commentaires avec photos",
      "quesAns":"Avec le vendeur Q&A",
      "addBasket": "ajouter au panier",
      "throwBasket" :"supprimer du panier",
      "question":"question du client",
      "answer":"réponse du vendeur",
      "noProductAlertT":"Il n'y a aucun produit ici.",
      "noProductAlert":"Vous n'avez pas ajouté de produit",
      "pricesT":"Totale" , 
      "alladresslink":"Voir toutes les adresses",
      "adress1":"Adresse du domicile 1",
      "adress2":"Adresse du domicile 2",
      "adressT":"Mis Direcciones Registradas",
      "information":"Mes informations",
      "namesurn":"Votre nom",
      "emaill":"Email",
      "orderT":"Mes Commandes",
      "allorders":"voir tout",
      "favT":"Mes Favoris",
      "cargo":"cargaison",
      "productinfos" :"détails du produit",
      "productsize":"corps",
      "totalstock":"stock total:",
      "productcolor" :"couleur du produit",
      "sortingProducts":"lister les produits",
      "showMore" : "Afficher plus",
      "showAll" :"Tout afficher",
      "mostLiked" :"Les plus aimés",
      "liked" :"Etres chers",
      "lessLiked" :"Msoins aimés",
      "favProducts" :"Produits préférés",
      "noProductAlert" : "Il n'y a pas encore de produits ajoutés ",
      "comingFromYou" :"Venant de toi",
      "photoComments": "Commentaires avec photos",
      "yourComments" :"Vos commentaires",
      "star" :"étoile",
      "productsOfSomething":"produits",
      "phone":"Téléphone",
      "socialMedia":"Réseaux Sociaux",
    }, 

    es: {
      "signin": "Iniciar sesión",
      "exit": "Cerrar sesión",
      "language": "Opciones de idioma",
      "AboutUs": "Acerca de nosotros",
      "prof" : "Perfil",
      "Products": "Productos",
      "Menu": "Menú",
      "Opportunities": "Oportunidades",
      "Contact": "Contacto",
      "contact": "Contacto",
      "myshopping": "Mis compras",
      "special": "Especial para ti",
      "Mybox": "Mi carrito",
      "service": "Nuestros servicios",
      "closeCom": "Cerrar publicidad",
      "openCom": "Abrir publicidad",
      "goLink": "Ir al enlace",
      "comp1title1": "Ofertas de verano",
      "comp1title2": "Viernes Negro",
      "comp1title3": "Grandes descuentos",
      "comp1p": "Válido solo para algunas tarjetas",
      "goProducts": "Ir a los productos",
      "winterDisc": "Descuentos de invierno",
      "winterDiscP": "No te pierdas los productos",
      "company2T1": "No te pierdas las ofertas, haz clic ahora",
      "company2T2": "Ofertas válidas para ciertas tarjetas",
      "company2T3": "Haz clic para el código de descuento",
      "whatsnew":"Que hay en oferta",
      "yourname": "Tu nombre",
      "yourpass": "Tu contraseña",
      "login": "Iniciar sesión",
      "createLog": "Crear cuenta",
      "SignIn": "Iniciar sesión",
      "email": "Correo electrónico",
      "Password": "Contraseña",
      "Name": "Nombre",
      "Surname": "Apellido",
      "SignUp": "Registrarse",
      "ShowT": "Bienvenido a nuestra comunidad",
      "ShowH": "QUEDA UN ÚLTIMO PASO",
      "ShowP": "Introduce el código enviado a tu correo electrónico para confirmar tu cuenta",
      "ShowBt1": "Confirmar",
      "ShowBt2": "Volver a recibir el código",
      "closetCompT": "¡Gran campaña en los armarios!",
      "closetCompP": "(válido para algunas tarjetas)",
      "closetCompT1": "Vendedor exitoso",
      "closetCompT2": "2500+ Favoritos",
      "closetCompB": "Ir al producto",
      "navSearch": "¿Qué estás buscando?",
      "deneme": "prueba",
      "navListS1": "Listar Productosi",
      "navListS2": "Parte inferior",
      "navListS3": "Casa",
      "navListS6": "Regalo de Joyas",
      "navListSI1": "suéter",
      "navListSI2": "blusa",
      "navListSI3": "falda",
      "navListSI4": "pantalón",
      "navListSI5": "estado",
      "navListSI6": "armario",
      "navListSI11": "anillo",
      "navListSI12": "collar",
      "filterT" :"productos de filtrado" , 
      "filterI1": "Tamaño",
      "filterI2": "Color",
      "filterI3": "Tarifa salarial",
      "filterIT1": "tamaño del cuerpo",
      "filterIT2": "longitud",
      "filterIT3": "anchura",
      "filterIO1": "blanco",
      "filterIO2": "negro",
      "filterIO3": "beige",
      "filterIO4": "rojo",
      "filterIO5": "amarillo",
      "filterIO6": "azul",
       "lookat": "Productos Similares",
       "alertsuccT": "¡Añadido al carrito con éxito!",
       "alertsuccD": "Puedes ver el producto en tu carrito",
       "alerterrT": "El producto no pudo ser añadido al carrito",
       "alerterrD": "Debes iniciar sesión primero",
       "commT": "Comentarios",
       "commTP": "Comentarios con fotos",
       "quesAns":"Con el vendedor Q&A",
       "comm1": "Me gustó, pero el color no es tan vibrante como en la foto",
       "comm2": "Definitivamente debes comprarlo por la relación calidad/precio.",
       "comm3": "Bueno, no estoy seguro, tal vez 5 de 10.",
       "comm4": "Si vas a comprar, toma una talla más grande, chicas",
       "comm5": "No es demasiado grueso, es para la temporada",
       "comm6": "¡Cómpralo, haz que otros lo compren!",
       "addBasket": "añadir al carrito",
       "throwBasket": "eliminar del carrito",
       "question":"pregunta del cliente",
       "answer":"respuesta del vendedor",
       "noProductAlertT":"No hay ningún producto aquí.",
       "noProductAlert":"No agregaste un producto",
       "pricesT":"Total" , 
       "alladresslink":"Ver todas las direcciones",
       "adress1":"Domicilio 1",
       "adress2":"Domicilio 2",
       "adressT":"Mis Direcciones Registradas",
      "information":"Mi Información",
      "namesurn":"Su nombre",
      "emaill":"Email",
      "orderT":"Mis Ordenes",
      "allorders":"ver todo",
      "favT":"Mis Favoritos",
      "cargo":"carga",
      "productinfos" :"detalles del producto",
      "productsize":"cuerpo",
      "totalstock":"stock total",
      "productcolor" :"color del producto",
      "sortingProducts":"lista de productos",
      "showMore" : "Mostrar más",
      "showAll" :"Mostrar todo",
      "mostLiked" :"Seres más queridos",
      "liked" :"Seres queridos",
      "lessLiked" :"Menos seres queridos",
      "favProducts" :"Productos favoritos",
      "noProductAlert" : "Aún no hay productos añadidos ",
      "comingFromYou" :"Viniendo de ti",
      "photoComments": "Comentarios con fotos",
      "yourComments" :"Sus comentarios",
      "star" : "estrella",
      "productsOfSomething":"productos",
      "phone":"Teléfono",
      "socialMedia":"Redes Sociales",

      
    },
    
    
  };

  // Varsayılan locale kontrolü
  const isLocale = localStorage.getItem("locale");
  const defaultLocale = isLocale ? isLocale : navigator.language.split("-")[0]; // Bölgesel dil kodunu alır, örn: 'en', 'tr'

  const [locale, setLocale] = useState(defaultLocale);

  useEffect(() => {
    localStorage.setItem("locale", locale); // locale'yi localStorage'a kaydet
  }, [locale]);

  // Dil değiştirme fonksiyonu
  const changeLanguage = (newLocale) => {
    setLocale(newLocale);
  };

  const values = { messages, locale, changeLanguage }; 

  return <LangContext.Provider value={values}>{children}</LangContext.Provider>;
};

// Context'ten verileri almak için custom hook
export const useLang = () => useContext(LangContext);
